# SPDX-License-Identifier: GPL-3.0-or-later
#
# Jaws Unleashed reverse engineering tools
# Copyright (C) 2026 MrDerpus and contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""List the game's on-screen messages with their numbers (2026-10-04).

    python3 scripts/dump_messages.py [OUT.txt]      (default: docs/game_messages.txt)

Jaws.exe keeps 5 language tables of message pointers; [0x854D14 + 4*lang]
points at each (English first, at 0x84FEF0). At startup FUN_00453ac0 puts
every English message into a case-insensitive hash (text -> number); the
lookup FUN_00453d00(text) returns tables[lang][number - 1], lang from
[0x920E24]+0x38. So code asks for a message by its English text, and the
pointer in the table decides what is shown. The mod's message overrides
(C:\\jaws_messages.txt) repoint these table slots; the slot numbers printed
here are the ones it uses (0-based table index).
"""
import struct
import sys

EXE = 'game_binary/Jaws.exe'
SECS = [(0x401000, 0x3CD000, 0x1000), (0x7CE000, 0x77000, 0x3CE000), (0x845000, 0x627000, 0x445000)]
LANG_TABLES, COUNT = 0x854D14, 1000


def va2off(va):
    for v, s, f in SECS:
        if v <= va < v + s:
            return va - v + f
    return None


def main(out):
    d = open(EXE, 'rb').read()
    u32 = lambda va: struct.unpack_from('<I', d, va2off(va))[0]
    table = u32(LANG_TABLES)
    lines = ['# Jaws.exe English message table (slot: text). Generated by scripts/dump_messages.py.',
             '# Use the slot number in C:\\jaws_messages.txt to replace a message (see mod/README.md).']
    for i in range(COUNT):
        p = va2off(u32(table + 4 * i))
        if p is None:
            continue
        s = d[p:d.find(b'\0', p)].decode('latin1')
        lines.append(f'{i}: ' + s.replace('\n', '\\n'))
    open(out, 'w').write('\n'.join(lines) + '\n')
    print(f'{len(lines) - 2} messages -> {out}')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else 'docs/game_messages.txt')
